name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.5

    # Step 3: Set up Azure credentials
    - name: Set up Azure credentials
      run: |
        # Configure Azure CLI to use the secrets stored in GitHub Secrets
        ls
        cd ResourceGroup
        pwd
        ls
        echo "Setting up Azure CLI credentials"
        az login --service-principal \
          --username "${{ secrets.CLIENTID }}" \
          --password "${{ secrets.CLIENTSECRET }}" \
          --tenant "${{ secrets.TENANTID }}"
          
        echo "Check subscription"
        # Set the subscription context
        az account set --subscription "${{ secrets.SUBSCRIPTIONID }}"

    # Step 4: Initialize Terraform
    - name: Terraform Init
      working-directory: ResourceGroup
      run: terraform init

    # Step 5: Run Terraform Plan
    - name: Terraform Plan
      working-directory: ResourceGroup
      run: terraform plan

    # Step 6: Apply Terraform Changes (run only on main branch)
    - name: Terraform Apply
      working-directory: ResourceGroup
      run: terraform apply -var-file="ResourceGroup.tfvars" -auto-approve
      if: github.ref == 'refs/heads/main'
